name: diali
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+1
  path_provider: ^2.0.14
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  image: ^4.0.15
  flutter_phone_direct_caller: ^2.0.0
 
  
  
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Regular.otf
          weight: 400

    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text/SF-Pro-Text-Regular.otf
          weight: 400

    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Regular.ttf
          weight: 400
          
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
